# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{

  users.groups.battery_ctl = {};


  services.thermald.enable = true;
  services.power-profiles-daemon.enable = false;

  hardware = {
		bluetooth = {
			enable = true;
			powerOnBoot = true;
			settings = {
				General = {
					Enable = "Source,Sinc,Media,Socket";
					Experimental = true;
				};
			};
		};
		graphics = {
			enable = true;
      enable32Bit = true;
			extraPackages = with pkgs; [
				intel-media-driver
				libvdpau-va-gl
			];
      extraPackages32 = with pkgs.pkgsi686Linux; [
        intel-media-driver
        libvdpau-va-gl
      ];
		};
	};

  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
